apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://harvester.fun-pumpkins.net/k8s/clusters/local"
    certificate-authority-data: "MIIB0jCCAXegAwIBAgIIR4ln6kKJsRAwCgYIKoZIzj0EAwIwRjEcMBoGA1UEChMTZHluYW1pY2xpc3RlbmVyLW9yZzEmMCQGA1UEAwwdZHluYW1pY2xpc3RlbmVyLWNhQDE3NDUxOTk5ODUwHhcNMjUwNDIxMDE0NjI1WhcNMjYwNDMwMTczNDM2WjAkMRAwDgYDVQQKEwdkeW5hbWljMRAwDgYDVQQDEwdkeW5hbWljMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgApKUDWn842Ch/LKYqwvPfcJd/yZTBhQ06zVwiq5+tzxG5/6M3D7Q369wvFdiz7wLvNa2eRL22vgXpRCchZdSaNxMG8wDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB8GA1UdIwQYMBaAFCTO06zC2f/M1Be0Xd1nK5sZsZ6qMCcGA1UdEQQgMB6HBAo0AAaHBAo0AEeHBAo0ASyHBAo1J2iHBKwQAWQwCgYIKoZIzj0EAwIDSQAwRgIhALpKqalWO+jCblP9QZtF9r6C9105ZuiNfkgwvllHphyuAiEA0Yl5jb3s5NLR/aKb3FXAexr0qbc4ouLrqzGJfgpCzds="
users:
- name: "local"
  user:
    token: "kubeconfig-user-zv76w8k87s:q425tgjzjj9ft52g4px9hbxgv462xq98nzh5pps9zrxcc8wcgxvll9"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
