version: "3.7"
services:
  minio:
    image: docker.io/bitnami/minio:2025.4.22-debian-12-r0
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - '/mnt/s3-vm-backup:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9090"
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge