version: "3.7"
services:
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - '/mnt/s3-vm-backup:/bitnami/minio/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /bitnami/minio/data --console-address ":9090"
volumes:
  minio_data:
    driver: local