apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fleet-vm-01
  namespace: default # or your target namespace
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app: fleet-vm-01
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          interfaces:
          - bridge: {}
            name: default
            model: virtio
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: fleet-vm-01-disk
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: fleet-vm-01
            ssh_authorized_keys:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAP+tW85n9PNJCxd9dfbwq4Afgkn8pYY+qoiaCA+7gD2
  dataVolumeTemplates:
  - metadata:
      name: fleet-vm-01-disk
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      sourceRef:
        kind: HarvesterImage
        name: "ubuntu-24" # Replace with your imported image name
        namespace: "default" # Or the namespace of your image
