# Example vm-definition.yml for creating a VM
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: my-fleet-vm
  namespace: default
spec:
  template:
    metadata:
      labels:
        harvesterhci.io/vmName: my-fleet-vm
    spec:
      cpu:
        cores: 2
      memory: 4Gi
      volumes:
        - name: rootdisk
          volumeSource:
            virtualMachineImage:
              name: ubuntu-24
              namespace: default
          size: 20Gi
          bus: virtio
      networks:
        - name: default
          networkType: L2
          model: virtio