apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-cloud-credential
  namespace: fleet-default
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: wait-for-secret
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for harvester-cloud-credential secret..."
          until kubectl get secret harvester-cloud-credential -n cattle-global-data; do
            sleep 5
          done
          echo "Secret found, proceeding."
