# Example vm-definition.yml for creating a VM
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/os: ''
  name: my-fleet-vm
  namespace: default

spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        harvesterhci.io/vmName: my-fleet-vm
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk-1
            - disk:
                bus: virtio
              name: cloudinitdisk
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - bridge: {}
              model: virtio
              name: default
        features:
          acpi:
            enabled: true
        machine:
          type: q35
        memory:
          guest: 4Gi
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: 125m
            memory: 2730Mi
      networks:
        - multus:
            networkName: default/vm-network
          name: default
      volumes:
        - name: disk-1
          volumeSource:
            virtualMachineImage:
              name: ubuntu-24
              namespace: default
          size: 20Gi
          bus: virtio