apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: new-vm
  namespace: default
spec:
  runStrategy: RerunOnFailure
  template:
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks: []
          interfaces:
            - bridge: {}
              model: virtio
              name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 4G
          limits:
            cpu: 2
            memory: "4Gi"
      networks:
        - multus:
            networkName: default/vm-network
          name: default
          pod: {}