apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: basic-vm
  namespace: default
  labels:
    app: basic-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: basic-vm
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - bridge: {}
              model: virtio
              name: default
            - masquerade: {}
              model: virtio
              name: mgmt-nic
      networks:
        - multus:
            networkName: default/vm-network
          name: default
        - name: mgmt-nic
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: basic-vm-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: basic-vm
              users:
                - name: rjouben
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAP+tW85n9PNJCxd9dfbwq4Afgkn8pYY+qoiaCA+7gD2"
              package_update: true
              package_upgrade: true
      volumeClaimTemplates:
        - metadata:
            name: basic-vm-rootdisk
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 40Gi
            storageClassName: ubuntu-24-encrypted
            dataSource:
              kind: HarvesterImage
              name: ubuntu-24-encrypted         # Harvester Image name
              namespace: default
