apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fleet-app-vm
  namespace: default
spec:
  running: true             # start manually after DV is ready
  template:
    metadata:
      labels:
        kubevirt.io/domain: fleet-app-vm
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        resources:
          requests:
            memory: 4Gi
        devices:
          disks:
            - name: fleet-vm-disk-0
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - bridge: {}
              name: vm-network
      networks:
        - multus:
            networkName: default/vm-network
          name: vm-network
      volumes:
        - name: fleet-vm-disk-0
          dataVolume:
            name: fleet-vm-disk-0
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: fleet-app-vm
              users:
                - name: rjouben
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAP+tW85n9PNJCxd9dfbwq4Afgkn8pYY+qoiaCA+7gD2"
              package_update: true
              package_upgrade: true

  dataVolumeTemplates:
    - metadata:
        name: fleet-vm-disk-0
        annotations:
          cdi.kubevirt.io/cloneType: host   # Force host-assisted clon        
      spec:
        source:
          # OR better if using Harvester image:
        #  pvc: null
        #  http: null
        # sourceRef:
          # kind: VirtualMachineImage
          # apiGroup: harvesterhci.io
          # name: ubuntu-24  
         source:
           pvc:                      # 👈 clone from existing PVC (the cloned Harvester image)
             namespace: default
             name: vmi-124b33ee-1dd7-46be-aab7-4a3a447f4f78   # 👈 replace with the PVC name of your cloned image
        pvc:
          accessModes: 
            - ReadWriteMany
          resources:
            requests:
              storage: 10Gi
          storageClassName: ubuntu-24-encrypted
          volumeMode: Block
        cloneStrategy: host        
