apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fleet-vm
  namespace: default
  labels:
    app: fleet-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: fleet-vm
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4Gi
        devices:
          disks:
            - name: disk-0
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: fleet-vm-disk-0
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: fleet-vm
              users:
                - name: rjouben
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAP+tW85n9PNJCxd9dfbwq4Afgkn8pYY+qoiaCA+7gD2"
              package_update: true
              package_upgrade: true
      volumeClaimTemplates:
        - metadata:
            name: fleet-vm-disk-0
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 40Gi
            storageClassName: ubuntu-24-encrypted   # Adjust to your storage class
            dataSource:
              kind: PersistentVolumeClaim
              name: ubuntu-24-encrypted
              namespace: default