apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: basic-fleet-vm
  namespace: default
  labels:
    app: basic-fleet-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: basic-fleet-vm
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - name: disk0
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 2Gi
      volumes:
      - name: disk0
        containerDisk:
          image: registry.suse.com/suse/sle15:latest
      networks:
      - name: default
        pod: {}
