apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: fleet-default
spec:
  kubernetesVersion: {{ .Values.kubernetesVersion }}
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecret }}
  rkeConfig:
    machinePools:
      - name: {{ .Values.machinePool.name }}
        quantity: {{ .Values.machinePool.quantity }}
        controlPlaneRole: {{ .Values.machinePool.roles.controlPlane }}
        etcdRole: {{ .Values.machinePool.roles.etcd }}
        workerRole: {{ .Values.machinePool.roles.worker }}
        machineConfigRef:
          kind: HarvesterConfig
          name: {{ .Values.machinePool.configName }}
    machineGlobalConfig:
      disable:
        - rke2-ingress-nginx
      cni: canal
      selinux: true
